#!/usr/bin/env perl
use warnings;
use strict;
#
# Find upnp devices and show something about them
#
#

# allow the libs to be in the bin dir
use FindBin;
use lib "$FindBin::RealBin/lib";
use lib "/home/hamish/s/bin/lib";

use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Quotekeys = 0;

use HC::Common;
use CommandLine;

my $option = {
};
my @option_list = (
    "verbose|v+",
    "debug",
);

sub main() {
    HC::Common::do_options($option,@option_list);
    return if (defined($option->{help}));

    $CommandLine::VERBOSE = $option->{verbose};

    my $result = CommandLine->HANDLE(@ARGV);
    if (!defined($result)) {
        print "Unknown command\n";
        exit 1
    }
    return $result;
}
main();

